### PR TITLE
Document _Alignof(max_align_t)

### PR DESCRIPTION
**Pull request by gnzlbg**

### CODE REVIEW

**Comment by hjl-tools** [comment]
Please send  x86-64 psABI changes to https://gitlab.com/x86-psABIs/x86-64-ABI

**Comment by gnzlbg** [comment]
This change is for the Intel386 ABI.

**Comment by hjl-tools** [comment]
For i386 psABI, please use https://gitlab.com/x86-psABIs/i386-ABI

**Comment by gnzlbg** [comment]
@hjl-tools it appears there is no merge request for this patch on gitlab yet

**Comment by hjl-tools** [comment]
Both patches have been checked in on gitlab.

**Comment by gnzlbg** [comment]
Thank you so much, have a great day!

**Comment by gnzlbg** [comment]
@hjl-tools https://gitlab.com/x86-psABIs/i386-ABI doesn't show this patch on master yet, was it checked to a different branch ?

**Comment by gnzlbg** [comment]
Also, would it be possible to produce new PDFs of the drafts with this change ?

**Pull request closed without merging**
