### PR TITLE
Document _Alignof(max_align_t)

### PR DESCRIPTION
**Pull request by gnzlbg**
This documents the "fundamental alignment" (per [C18 6.2.8.2](https://web.archive.org/web/20181230041359if_/http://www.open-std.org/jtc1/sc22/wg14/www/abq/c17_updated_proposed_fdis.pdf)) of the ABI. Fundamental alignments shall be supported by the implementation for objects of all storage durations.

### CODE REVIEW

**Comment by hjl-tools** [comment]
Please send  x86-64 psABI changes to https://gitlab.com/x86-psABIs/x86-64-ABI

**Comment by gnzlbg** [comment]
I can't find that branch mirrored here, or is it under a different name?

**Comment by hjl-tools** [comment]
Please use gitlab.com to submit x86-64 psABI patches.

**Comment by gnzlbg** [comment]
Can I send you the patch per email ? I don't have a gitlab account.

**Comment by hjl-tools** [comment]
All x86-64 psABI patches should be sent to x86-64 mailing list.

**Comment by gnzlbg** [comment]
@hjl-tools ok, I've sent the two patches to the mailing list: https://groups.google.com/forum/#!topic/x86-64-abi/gCxcMiaVF2M

**Comment by gnzlbg** [comment]
@hjl-tools were the two patches applied to the corresponding branches ? Or did I send them to the wrong mailing list ?

**Comment by hjl-tools** [comment]
i386 psABI change should be sent to https://groups.google.com/forum/#!forum/ia32-abi

**Comment by gnzlbg** [comment]
Ok, I will do that, need to register there first. 

Does that mean that the x86 change was merged? Or how can I track its progress?

**Pull request closed without merging**
